set -g history-limit 100000
set -g default-terminal "screen-256color"

set-window-option -g mode-keys vi

# prefix keys
unbind C-b
set-option -g prefix C-_                # Ctrl+/
set-option -g prefix2 M-z
bind-key C-_ send-prefix
bind-key M-z send-prefix -2

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# set mouse on

bind r display-message "Sourcing ~/.tmux.conf" \; source-file ~/.tmux.conf
